# Generated by Django 5.1.7 on 2025-04-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_order_status_order_alter_order_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowers',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='количество в наличии'),
        ),
    ]
