# Generated by Django 5.1.7 on 2025-03-24 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_flowers_image_four_flowers_image_three_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flowers',
            name='image',
        ),
        migrations.RemoveField(
            model_name='flowers',
            name='image_four',
        ),
        migrations.RemoveField(
            model_name='flowers',
            name='image_three',
        ),
        migrations.RemoveField(
            model_name='flowers',
            name='image_two',
        ),
        migrations.CreateModel(
            name='FlowerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/', verbose_name='Изображение')),
                ('flower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.flowers', verbose_name='цветок')),
            ],
        ),
    ]
