# Generated by Django 5.1.7 on 2025-03-24 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_flowers_image_remove_flowers_image_four_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flowerimage',
            options={'verbose_name': 'изображение', 'verbose_name_plural': 'изображения'},
        ),
    ]
