# Generated by Django 5.1.7 on 2025-04-30 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='position',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='blog.flowers'),
            preserve_default=False,
        ),
    ]
