# Generated by Django 5.1.7 on 2025-04-30 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_order_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='position',
        ),
    ]
