# Generated by Django 5.1.7 on 2025-03-24 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_flowerimage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowerimage',
            name='flower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.flowers', verbose_name='цветок'),
        ),
    ]
