# Generated by Django 5.1.7 on 2025-03-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_flowerimage_flower'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowers',
            name='image',
            field=models.ImageField(default='', upload_to='uploads/', verbose_name='картинки'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FlowerImage',
        ),
    ]
