# Generated by Django 5.1.7 on 2025-05-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_order_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertime',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='количество'),
        ),
        migrations.AlterField(
            model_name='ordertime',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='цена за единицу'),
        ),
    ]
