# Generated by Django 5.1.7 on 2025-03-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_flowers_image_delete_flowerimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowers',
            name='image_two',
            field=models.ImageField(default=' ', upload_to='uploads/', verbose_name='вторая картинка'),
            preserve_default=False,
        ),
    ]
