# Generated by Django 5.1.7 on 2025-03-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_basket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='stock_basket',
        ),
        migrations.AddField(
            model_name='basket',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='количество'),
        ),
    ]
